services:
  env:
    container_name: compEnv
    image: go-competitive-env
    build:
      context: .
    tty: true
    volumes:
      - type: bind
        source: home/work
        target: /home/work
